const std = @import("std");
const ast = @import("ast.zig");

pub const Ident = ast.Ident;
pub const ObjectName = ast.ObjectName;
pub const Expr = ast.Expr;
pub const DataType = ast.DataType;
pub const Query = ast.Query;

// ---------------------------------------------------------------------------
// Referential action
// ---------------------------------------------------------------------------

/// Actions for ON DELETE / ON UPDATE in foreign key constraints.
pub const ReferentialAction = enum {
    restrict,
    cascade,
    set_null,
    no_action,
    set_default,
};

/// Drop behavior: CASCADE or RESTRICT.
pub const DropBehavior = enum {
    restrict,
    cascade,
};

// ---------------------------------------------------------------------------
// Column options
// ---------------------------------------------------------------------------

/// How a generated/computed column is stored.
pub const GeneratedAs = enum {
    /// GENERATED ALWAYS
    always,
    /// GENERATED BY DEFAULT (for identity columns)
    by_default,
};

/// VIRTUAL or STORED for generated expressions.
pub const GeneratedExpressionMode = enum {
    virtual,
    stored,
};

/// AUTO_INCREMENT seed and increment parameters.
pub const IdentityParams = struct {
    seed: Expr,
    increment: Expr,
};

/// Column constraint: REFERENCES table [(cols)] [ON DELETE ...] [ON UPDATE ...]
pub const ForeignKeyConstraint = struct {
    /// Referenced table.
    foreign_table: ObjectName,
    /// Referenced columns (may be empty when referencing PK).
    referred_columns: []const Ident,
    /// ON DELETE action.
    on_delete: ?ReferentialAction,
    /// ON UPDATE action.
    on_update: ?ReferentialAction,
};

/// A column-level option (modifier after the type in CREATE TABLE).
pub const ColumnOption = union(enum) {
    /// NULL
    null,
    /// NOT NULL
    not_null,
    /// DEFAULT expr
    default: Expr,
    /// PRIMARY KEY
    primary_key,
    /// UNIQUE
    unique,
    /// REFERENCES (foreign key)
    foreign_key: ForeignKeyConstraint,
    /// CHECK (expr)
    check: Expr,
    /// AUTO_INCREMENT (MySQL)
    auto_increment,
    /// COMMENT 'text' (MySQL)
    comment: []const u8,
    /// CHARACTER SET name (MySQL)
    character_set: ObjectName,
    /// COLLATE name
    collate: ObjectName,
    /// ON UPDATE expr (MySQL, for TIMESTAMP columns)
    on_update: Expr,
    /// GENERATED ... AS ... [VIRTUAL|STORED]
    generated: struct {
        generated_as: GeneratedAs,
        generation_expr: ?*const Expr,
        generation_expr_mode: ?GeneratedExpressionMode,
    },
    /// INVISIBLE (MySQL 8.0+)
    invisible,
};

/// An optionally-named column option: `[CONSTRAINT name] <option>`.
pub const ColumnOptionDef = struct {
    /// Optional constraint name.
    name: ?Ident,
    /// The column option.
    option: ColumnOption,
};

// ---------------------------------------------------------------------------
// Column definition
// ---------------------------------------------------------------------------

/// A column definition in CREATE TABLE or ALTER TABLE ADD COLUMN.
pub const ColumnDef = struct {
    /// Column name.
    name: Ident,
    /// Column data type.
    data_type: DataType,
    /// Column options (NOT NULL, DEFAULT, PRIMARY KEY, etc.).
    options: []const ColumnOptionDef,
};

// ---------------------------------------------------------------------------
// MySQL column position
// ---------------------------------------------------------------------------

/// Position modifier for MySQL ALTER TABLE MODIFY/CHANGE COLUMN.
pub const MySQLColumnPosition = union(enum) {
    /// FIRST
    first,
    /// AFTER column_name
    after: Ident,
};

// ---------------------------------------------------------------------------
// Table constraints
// ---------------------------------------------------------------------------

/// A table-level constraint in CREATE TABLE.
pub const TableConstraint = union(enum) {
    /// PRIMARY KEY (cols)
    primary_key: struct {
        name: ?Ident,
        columns: []const Ident,
    },
    /// UNIQUE (cols) or UNIQUE KEY name (cols)
    unique: struct {
        name: ?Ident,
        columns: []const Ident,
    },
    /// FOREIGN KEY (cols) REFERENCES table (cols) [ON DELETE ...] [ON UPDATE ...]
    foreign_key: struct {
        name: ?Ident,
        columns: []const Ident,
        foreign_table: ObjectName,
        referred_columns: []const Ident,
        on_delete: ?ReferentialAction,
        on_update: ?ReferentialAction,
    },
    /// CHECK (expr)
    check: struct {
        name: ?Ident,
        expr: Expr,
    },
    /// INDEX / KEY name (cols) (MySQL)
    index: struct {
        name: ?Ident,
        columns: []const Ident,
    },
    /// FULLTEXT [INDEX] name (cols) (MySQL)
    fulltext: struct {
        name: ?Ident,
        columns: []const Ident,
    },
    /// SPATIAL [INDEX] name (cols) (MySQL)
    spatial: struct {
        name: ?Ident,
        columns: []const Ident,
    },
};

// ---------------------------------------------------------------------------
// Index column (for CREATE INDEX)
// ---------------------------------------------------------------------------

/// A column reference in an index, optionally with sort order.
pub const IndexColumn = struct {
    /// Column expression (usually an identifier).
    column: Expr,
    /// Optional sort direction for the indexed column.
    asc: ?bool,
};

// ---------------------------------------------------------------------------
// ALTER TABLE operation
// ---------------------------------------------------------------------------

/// Operations that can be performed in an ALTER TABLE statement.
pub const AlterTableOperation = union(enum) {
    /// ADD [COLUMN] [IF NOT EXISTS] col_def [FIRST | AFTER col]
    add_column: struct {
        column_keyword: bool,
        if_not_exists: bool,
        column_def: ColumnDef,
        column_position: ?MySQLColumnPosition,
    },
    /// DROP [COLUMN] [IF EXISTS] col
    drop_column: struct {
        column_name: Ident,
        if_exists: bool,
        drop_behavior: ?DropBehavior,
    },
    /// MODIFY COLUMN col type [options] (MySQL)
    modify_column: struct {
        col_name: Ident,
        data_type: DataType,
        options: []const ColumnOptionDef,
        column_position: ?MySQLColumnPosition,
    },
    /// CHANGE COLUMN old_name new_name type [options] (MySQL)
    change_column: struct {
        old_name: Ident,
        new_name: Ident,
        data_type: DataType,
        options: []const ColumnOptionDef,
        column_position: ?MySQLColumnPosition,
    },
    /// RENAME COLUMN old TO new
    rename_column: struct { old_column_name: Ident, new_column_name: Ident },
    /// RENAME [TO] new_name
    rename_table: ObjectName,
    /// ADD CONSTRAINT [name] table_constraint
    add_constraint: struct {
        constraint: TableConstraint,
        not_valid: bool,
    },
    /// DROP CONSTRAINT [IF EXISTS] name [CASCADE | RESTRICT]
    drop_constraint: struct {
        if_exists: bool,
        name: Ident,
        drop_behavior: ?DropBehavior,
    },
    /// DROP PRIMARY KEY
    drop_primary_key,
    /// DROP INDEX name (MySQL)
    drop_index: Ident,
    /// ALTER COLUMN name SET DEFAULT expr / DROP DEFAULT / SET NOT NULL / etc.
    alter_column: struct {
        column_name: Ident,
        op: AlterColumnOperation,
    },
};

/// Operations valid for ALTER COLUMN.
pub const AlterColumnOperation = union(enum) {
    set_not_null,
    drop_not_null,
    set_default: Expr,
    drop_default,
    set_data_type: struct {
        data_type: DataType,
    },
};

// ---------------------------------------------------------------------------
// ALTER TABLE
// ---------------------------------------------------------------------------

/// An ALTER TABLE statement.
pub const AlterTable = struct {
    /// `IF EXISTS` modifier.
    if_exists: bool,
    /// Target table name.
    name: ObjectName,
    /// The operations to perform.
    operations: []const AlterTableOperation,
    /// The last token of the statement (for span tracking).
    end_token: ?@import("tokenizer.zig").TokenWithSpan = null,
};

// ---------------------------------------------------------------------------
// CREATE TABLE
// ---------------------------------------------------------------------------

/// Comment definition variant (inline or after table name).
pub const CommentDef = union(enum) {
    /// COMMENT = 'text' style
    equals: []const u8,
    /// COMMENT 'text' style (no equals sign)
    simple: []const u8,
};

/// ON COMMIT behavior for temporary tables.
pub const OnCommit = enum {
    delete_rows,
    preserve_rows,
    drop,
};

/// A CREATE TABLE statement.
pub const CreateTable = struct {
    /// `OR REPLACE` modifier.
    or_replace: bool,
    /// `TEMPORARY` or `TEMP` modifier.
    temporary: bool,
    /// `IF NOT EXISTS` modifier.
    if_not_exists: bool,
    /// Table name.
    name: ObjectName,
    /// Column definitions.
    columns: []const ColumnDef,
    /// Table-level constraints.
    constraints: []const TableConstraint,
    /// MySQL table options (ENGINE, CHARSET, COMMENT, etc.) stored as key=value.
    table_options: []const TableOption,
    /// `ON COMMIT` behavior for temporary tables.
    on_commit: ?OnCommit,
    /// `LIKE other_table` (copy structure without data).
    like: ?ObjectName,
    /// `AS SELECT ...` clause.
    as_select: ?*const Query,
    /// Table-level COMMENT.
    comment: ?[]const u8,
};

/// A MySQL/generic table option (ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4, etc.).
pub const TableOption = union(enum) {
    /// ENGINE = name
    engine: []const u8,
    /// DEFAULT CHARSET = name / CHARACTER SET = name
    charset: []const u8,
    /// COLLATE = name
    collate: []const u8,
    /// COMMENT = 'text'
    comment: []const u8,
    /// AUTO_INCREMENT = n
    auto_increment: u64,
    /// Generic key = value option.
    other: struct { key: []const u8, value: []const u8 },
};

// ---------------------------------------------------------------------------
// CREATE INDEX
// ---------------------------------------------------------------------------

/// A CREATE INDEX statement.
pub const CreateIndex = struct {
    /// `IF NOT EXISTS` modifier.
    if_not_exists: bool,
    /// Index name (may be absent in some dialects).
    name: ?ObjectName,
    /// `UNIQUE` index.
    unique: bool,
    /// `FULLTEXT` index (MySQL).
    fulltext: bool,
    /// Table being indexed.
    table_name: ObjectName,
    /// Index columns.
    columns: []const IndexColumn,
    /// MySQL USING BTREE / HASH.
    using: ?[]const u8,
};

// ---------------------------------------------------------------------------
// CREATE VIEW
// ---------------------------------------------------------------------------

/// A CREATE VIEW statement.
pub const CreateView = struct {
    /// `OR REPLACE` modifier.
    or_replace: bool,
    /// View name.
    name: ObjectName,
    /// Optional explicit column list.
    columns: []const Ident,
    /// The query defining the view.
    query: *const Query,
    /// `WITH CHECK OPTION`.
    with_check_option: bool,
};

// ---------------------------------------------------------------------------
// DROP
// ---------------------------------------------------------------------------

/// What kind of object is being dropped.
pub const DropObjectType = enum {
    table,
    index,
    view,
    database,
};

/// A DROP statement.
pub const Drop = struct {
    /// The object type being dropped.
    object_type: DropObjectType,
    /// `IF EXISTS` modifier.
    if_exists: bool,
    /// Names of objects to drop.
    names: []const ObjectName,
    /// Optional `ON table_name` for DROP INDEX (MySQL).
    on_table: ?ObjectName,
    /// Optional cascade/restrict behavior.
    drop_behavior: ?DropBehavior,
    /// `TEMPORARY` modifier.
    temporary: bool,
};

test "ColumnDef compiles" {
    const col: ColumnDef = .{
        .name = .{ .value = "id", .quote_style = null },
        .data_type = .{ .int = null },
        .options = &.{},
    };
    try std.testing.expectEqualStrings("id", col.name.value);
}

test "CreateTable compiles" {
    const ct: CreateTable = .{
        .or_replace = false,
        .temporary = false,
        .if_not_exists = false,
        .name = .{ .parts = &.{} },
        .columns = &.{},
        .constraints = &.{},
        .table_options = &.{},
        .on_commit = null,
        .like = null,
        .as_select = null,
        .comment = null,
    };
    try std.testing.expect(!ct.temporary);
}

test "AlterTableOperation union" {
    const op: AlterTableOperation = .{ .drop_primary_key = {} };
    try std.testing.expect(op == .drop_primary_key);
}
