const std = @import("std");

/// All SQL keywords recognized by the parser.
/// The enum values are ordered alphabetically to allow binary search via the ALL_KEYWORDS table.
pub const Keyword = enum {
    NoKeyword,
    ABORT,
    ABS,
    ABSENT,
    ABSOLUTE,
    ACCESS,
    ACCOUNT,
    ACTION,
    ADD,
    ADMIN,
    AFTER,
    AGAINST,
    AGGREGATE,
    ALGORITHM,
    ALIAS,
    ALL,
    ALLOCATE,
    ALTER,
    ALWAYS,
    ANALYZE,
    AND,
    ANTI,
    ANY,
    APPLY,
    ARCHIVE,
    ARE,
    ARRAY,
    ARRAY_MAX_CARDINALITY,
    AS,
    ASC,
    ASENSITIVE,
    ASOF,
    ASSERT,
    ASYMMETRIC,
    AT,
    ATOMIC,
    ATTACH,
    AUDIT,
    AUTHORIZATION,
    AUTO,
    AUTOINCREMENT,
    AUTO_INCREMENT,
    AVG,
    BACKWARD,
    BEFORE,
    BEGIN,
    BEGIN_FRAME,
    BEGIN_PARTITION,
    BERNOULLI,
    BETWEEN,
    BIGINT,
    BINARY,
    BIT,
    BLOB,
    BLOCK,
    BOOL,
    BOOLEAN,
    BOTH,
    BROWSE,
    BTREE,
    BUCKET,
    BY,
    BYTES,
    CACHE,
    CALL,
    CALLED,
    CARDINALITY,
    CASCADE,
    CASCADED,
    CASE,
    CAST,
    CATALOG,
    CEIL,
    CEILING,
    CENTURY,
    CHAIN,
    CHANGE,
    CHAR,
    CHARACTER,
    CHARACTERISTICS,
    CHARACTERS,
    CHARACTER_LENGTH,
    CHARSET,
    CHAR_LENGTH,
    CHECK,
    CHECKSUM,
    CLOB,
    CLONE,
    CLOSE,
    CLUSTER,
    CLUSTERED,
    COALESCE,
    COLLATE,
    COLLATION,
    COLLECT,
    COLUMN,
    COLUMNS,
    COMMENT,
    COMMIT,
    COMMITTED,
    COMPRESS,
    COMPRESSION,
    COMPUTE,
    CONDITION,
    CONFLICT,
    CONNECT,
    CONNECTION,
    CONSTRAINT,
    CONTAINS,
    CONTINUE,
    CONVERT,
    COPY,
    CORR,
    CORRESPONDING,
    COUNT,
    COVAR_POP,
    COVAR_SAMP,
    CREATE,
    CROSS,
    CSV,
    CUBE,
    CUME_DIST,
    CURRENT,
    CURRENT_CATALOG,
    CURRENT_DATE,
    CURRENT_DEFAULT_TRANSFORM_GROUP,
    CURRENT_PATH,
    CURRENT_ROLE,
    CURRENT_ROW,
    CURRENT_SCHEMA,
    CURRENT_TIME,
    CURRENT_TIMESTAMP,
    CURRENT_TRANSFORM_GROUP_FOR_TYPE,
    CURRENT_USER,
    CURSOR,
    CYCLE,
    DATA,
    DATABASE,
    DATABASES,
    DATE,
    DATETIME,
    DAY,
    DAYOFWEEK,
    DAYOFYEAR,
    DAYS,
    DEALLOCATE,
    DEC,
    DECADE,
    DECIMAL,
    DECLARE,
    DEFAULT,
    DEFAULTS,
    DEFERRABLE,
    DEFERRED,
    DEFINE,
    DEFINER,
    DELAYED,
    DELETE,
    DELIMITER,
    DENSE_RANK,
    DESC,
    DESCRIBE,
    DETACH,
    DETERMINISTIC,
    DISABLE,
    DISCONNECT,
    DISTINCT,
    DISTINCTROW,
    DISTRIBUTE,
    DIV,
    DO,
    DOMAIN,
    DOUBLE,
    DROP,
    DUPLICATE,
    DYNAMIC,
    EACH,
    ELEMENT,
    ELSE,
    ELSEIF,
    EMPTY,
    ENABLE,
    ENCODING,
    ENCRYPTED,
    ENCRYPTION,
    END,
    END_FRAME,
    END_PARTITION,
    ENFORCED,
    ENGINE,
    ENUM,
    EPOCH,
    ERROR,
    ESCAPE,
    EXCEPT,
    EXCEPTION,
    EXCLUDE,
    EXCLUSIVE,
    EXEC,
    EXECUTE,
    EXISTS,
    EXP,
    EXPLAIN,
    EXPLICIT,
    EXPANSION,
    EXPORT,
    EXTERNAL,
    EXTRACT,
    FAIL,
    FALSE,
    FETCH,
    FIELDS,
    FILE,
    FILTER,
    FINAL,
    FIRST,
    FIRST_VALUE,
    FLOAT,
    FLOAT4,
    FLOAT8,
    FLOOR,
    FLUSH,
    FOLLOWING,
    FOR,
    FORCE,
    FOREIGN,
    FORMAT,
    FORWARD,
    FRAME_ROW,
    FREE,
    FROM,
    FULL,
    FULLTEXT,
    FUNCTION,
    FUNCTIONS,
    GENERATED,
    GLOBAL,
    GRANT,
    GRANTS,
    GROUP,
    GROUPING,
    GROUPS,
    HASH,
    HAVING,
    HEAP,
    HIGH_PRIORITY,
    HOLD,
    HOUR,
    HOURS,
    ID,
    IDENTIFIED,
    IDENTITY,
    IF,
    IGNORE,
    ILIKE,
    IMMEDIATE,
    IMMUTABLE,
    IN,
    INCLUDE,
    INCREMENT,
    INDEX,
    INDICATOR,
    INHERIT,
    INHERITS,
    INITIALIZE,
    INITIALLY,
    INNER,
    INOUT,
    INPUT,
    INSENSITIVE,
    INSERT,
    INSTANT,
    INSTEAD,
    INT,
    INT2,
    INT4,
    INT8,
    INTEGER,
    INTERSECT,
    INTERSECTION,
    INTERVAL,
    INTO,
    INVISIBLE,
    INVOKER,
    IS,
    ISOLATION,
    ITEMS,
    JOIN,
    JSON,
    KEY,
    KEYS,
    KEY_BLOCK_SIZE,
    KILL,
    LAG,
    LANGUAGE,
    LARGE,
    LAST,
    LAST_VALUE,
    LATERAL,
    LEAD,
    LEADING,
    LEAKPROOF,
    LEAST,
    LEFT,
    LEVEL,
    LIKE,
    LIKE_REGEX,
    LIMIT,
    LINES,
    LIST,
    LISTEN,
    LN,
    LOAD,
    LOCAL,
    LOCALTIME,
    LOCALTIMESTAMP,
    LOCATION,
    LOCK,
    LOCKED,
    LOG,
    LONG,
    LONGBLOB,
    LONGTEXT,
    LOWER,
    LOW_PRIORITY,
    MACRO,
    MANAGE,
    MANAGED,
    MAP,
    MATCH,
    MATCHED,
    MATCH_RECOGNIZE,
    MATERIALIZED,
    MAX,
    MAXVALUE,
    MAX_ROWS,
    MEDIUMBLOB,
    MEDIUMINT,
    MEDIUMTEXT,
    MEMBER,
    MERGE,
    METHOD,
    MICROSECOND,
    MICROSECONDS,
    MILLENNIUM,
    MILLISECOND,
    MILLISECONDS,
    MIN,
    MINUS,
    MINUTE,
    MINUTES,
    MINVALUE,
    MIN_ROWS,
    MOD,
    MODE,
    MODIFIES,
    MODIFY,
    MODULE,
    MONITOR,
    MONTH,
    MONTHS,
    MULTISET,
    NAME,
    NAMES,
    NANOSECOND,
    NANOSECONDS,
    NATIONAL,
    NATURAL,
    NCHAR,
    NCLOB,
    NEXT,
    NO,
    NOCYCLE,
    NONE,
    NORMALIZE,
    NORMALIZED,
    NOT,
    NOTHING,
    NOTIFY,
    NOWAIT,
    NO_WRITE_TO_BINLOG,
    NTH_VALUE,
    NTILE,
    NULL,
    NULLABLE,
    NULLIF,
    NULLS,
    NUMBER,
    NUMERIC,
    NVARCHAR,
    OBJECT,
    OCCURRENCES_REGEX,
    OCTETS,
    OCTET_LENGTH,
    OF,
    OFF,
    OFFSET,
    OLD,
    OMIT,
    ON,
    ONE,
    ONLY,
    OPEN,
    OPERATE,
    OPERATOR,
    OPTIMIZE,
    OPTION,
    OPTIONS,
    OR,
    ORDER,
    ORDINALITY,
    OTHER,
    OUT,
    OUTER,
    OUTPUT,
    OVER,
    OVERFLOW,
    OVERLAPS,
    OVERLAY,
    OVERRIDE,
    OVERWRITE,
    OWNED,
    OWNER,
    PARALLEL,
    PARAMETER,
    PARTIAL,
    PARTITION,
    PARTITIONED,
    PARTITIONS,
    PASSING,
    PASSWORD,
    PATH,
    PATTERN,
    PER,
    PERCENT,
    PERCENTILE_CONT,
    PERCENTILE_DISC,
    PERCENT_RANK,
    PERIOD,
    PIVOT,
    PLACING,
    POLICY,
    POOL,
    POSITION,
    POSITION_REGEX,
    POWER,
    PRECEDING,
    PRECISION,
    PREPARE,
    PRESERVE,
    PRIMARY,
    PRIOR,
    PRIVILEGES,
    PROCEDURE,
    PUBLIC,
    PURGE,
    QUALIFY,
    QUARTER,
    QUERIES,
    QUERY,
    QUOTE,
    RAISE,
    RANGE,
    RANK,
    READ,
    READS,
    READ_ONLY,
    REAL,
    RECURSIVE,
    REF,
    REFERENCES,
    REFERENCING,
    REFRESH,
    REGEXP,
    REGR_AVGX,
    REGR_AVGY,
    REGR_COUNT,
    REGR_INTERCEPT,
    REGR_R2,
    REGR_SLOPE,
    REGR_SXX,
    REGR_SXY,
    REGR_SYY,
    RELATIVE,
    RELEASE,
    REMAINDER,
    REMOTE,
    RENAME,
    REPEATABLE,
    REPLACE,
    REPLICA,
    REPLICATE,
    REPLICATION,
    REQUIRE,
    RESET,
    RESTRICT,
    RESULT,
    RETURN,
    RETURNING,
    RETURNS,
    REVOKE,
    RIGHT,
    RLIKE,
    ROLE,
    ROLES,
    ROLLBACK,
    ROLLUP,
    ROW,
    ROWID,
    ROWS,
    ROW_FORMAT,
    ROW_NUMBER,
    SAFE,
    SAMPLE,
    SAVEPOINT,
    SCHEMA,
    SCHEMAS,
    SCOPE,
    SCROLL,
    SEARCH,
    SECOND,
    SECONDS,
    SECURITY,
    SELECT,
    SEMI,
    SENSITIVE,
    SEPARATOR,
    SEQUENCE,
    SEQUENCES,
    SERIALIZABLE,
    SERVER,
    SERVICE,
    SESSION,
    SESSION_USER,
    SET,
    SETS,
    SHARE,
    SHOW,
    SIGNED,
    SIMILAR,
    SMALLINT,
    SNAPSHOT,
    SOME,
    SORT,
    SPATIAL,
    SQL,
    SQLEXCEPTION,
    SQLSTATE,
    SQLWARNING,
    SQL_BIG_RESULT,
    SQL_CALC_FOUND_ROWS,
    SQL_NO_CACHE,
    SQL_SMALL_RESULT,
    SQRT,
    STABLE,
    START,
    STARTS,
    STATEMENT,
    STATIC,
    STATISTICS,
    STATUS,
    STDDEV_POP,
    STDDEV_SAMP,
    STDIN,
    STDOUT,
    STORAGE,
    STORED,
    STRAIGHT_JOIN,
    STREAM,
    STRICT,
    STRING,
    STRUCT,
    SUBMULTISET,
    SUBSTR,
    SUBSTRING,
    SUBSTRING_REGEX,
    SUCCEEDS,
    SUM,
    SUPER,
    SUPERUSER,
    SUSPEND,
    SYMMETRIC,
    SYNONYM,
    SYSTEM,
    SYSTEM_TIME,
    SYSTEM_USER,
    TABLE,
    TABLES,
    TABLESAMPLE,
    TABLESPACE,
    TEMP,
    TEMPORARY,
    TEMPTABLE,
    TERMINATED,
    TEXT,
    THEN,
    TIES,
    TIME,
    TIMESTAMP,
    TIMESTAMPTZ,
    TIMETZ,
    TIMEZONE,
    TIMEZONE_HOUR,
    TIMEZONE_MINUTE,
    TINYBLOB,
    TINYINT,
    TINYTEXT,
    TO,
    TOP,
    TRAILING,
    TRANSACTION,
    TRANSLATE,
    TRANSLATE_REGEX,
    TRANSLATION,
    TREAT,
    TRIGGER,
    TRIM,
    TRIM_ARRAY,
    TRUE,
    TRUNCATE,
    TRY,
    TRY_CAST,
    TYPE,
    UBIGINT,
    UNBOUNDED,
    UNCOMMITTED,
    UNION,
    UNIQUE,
    UNKNOWN,
    UNLOCK,
    UNMATCHED,
    UNNEST,
    UNPIVOT,
    UNSIGNED,
    UNTIL,
    UPDATE,
    UPPER,
    USE,
    USER,
    USING,
    UUID,
    VACUUM,
    VALID,
    VALIDATE,
    VALUE,
    VALUES,
    VARBINARY,
    VARCHAR,
    VARCHAR2,
    VARIABLE,
    VARIABLES,
    VARYING,
    VAR_POP,
    VAR_SAMP,
    VERSION,
    VERSIONING,
    VIEW,
    VIEWS,
    VOLATILE,
    WEEK,
    WEEKS,
    WHEN,
    WHERE,
    WHILE,
    WIDTH_BUCKET,
    WINDOW,
    WITH,
    WITHIN,
    WITHOUT,
    WORK,
    WRITE,
    XOR,
    YEAR,
    YEARS,
    ZONE,

    pub fn toString(self: Keyword) []const u8 {
        return @tagName(self);
    }

    pub fn format(self: Keyword, writer: *std.Io.Writer) std.Io.Writer.Error!void {
        try writer.writeAll(self.toString());
    }
};

/// Sorted keyword-string -> Keyword pairs for binary search.
/// Each entry is (uppercase keyword string, Keyword enum value).
const KeywordEntry = struct {
    word: []const u8,
    kw: Keyword,
};

/// Sorted table of all keywords (uppercase strings) for binary-search lookup.
/// Sorted alphabetically by word.
const ALL_KEYWORDS: []const KeywordEntry = &.{
    .{ .word = "ABORT", .kw = .ABORT },
    .{ .word = "ABS", .kw = .ABS },
    .{ .word = "ABSENT", .kw = .ABSENT },
    .{ .word = "ABSOLUTE", .kw = .ABSOLUTE },
    .{ .word = "ACCESS", .kw = .ACCESS },
    .{ .word = "ACCOUNT", .kw = .ACCOUNT },
    .{ .word = "ACTION", .kw = .ACTION },
    .{ .word = "ADD", .kw = .ADD },
    .{ .word = "ADMIN", .kw = .ADMIN },
    .{ .word = "AFTER", .kw = .AFTER },
    .{ .word = "AGAINST", .kw = .AGAINST },
    .{ .word = "AGGREGATE", .kw = .AGGREGATE },
    .{ .word = "ALGORITHM", .kw = .ALGORITHM },
    .{ .word = "ALIAS", .kw = .ALIAS },
    .{ .word = "ALL", .kw = .ALL },
    .{ .word = "ALLOCATE", .kw = .ALLOCATE },
    .{ .word = "ALTER", .kw = .ALTER },
    .{ .word = "ALWAYS", .kw = .ALWAYS },
    .{ .word = "ANALYZE", .kw = .ANALYZE },
    .{ .word = "AND", .kw = .AND },
    .{ .word = "ANTI", .kw = .ANTI },
    .{ .word = "ANY", .kw = .ANY },
    .{ .word = "APPLY", .kw = .APPLY },
    .{ .word = "ARCHIVE", .kw = .ARCHIVE },
    .{ .word = "ARE", .kw = .ARE },
    .{ .word = "ARRAY", .kw = .ARRAY },
    .{ .word = "ARRAY_MAX_CARDINALITY", .kw = .ARRAY_MAX_CARDINALITY },
    .{ .word = "AS", .kw = .AS },
    .{ .word = "ASC", .kw = .ASC },
    .{ .word = "ASENSITIVE", .kw = .ASENSITIVE },
    .{ .word = "ASOF", .kw = .ASOF },
    .{ .word = "ASSERT", .kw = .ASSERT },
    .{ .word = "ASYMMETRIC", .kw = .ASYMMETRIC },
    .{ .word = "AT", .kw = .AT },
    .{ .word = "ATOMIC", .kw = .ATOMIC },
    .{ .word = "ATTACH", .kw = .ATTACH },
    .{ .word = "AUDIT", .kw = .AUDIT },
    .{ .word = "AUTHORIZATION", .kw = .AUTHORIZATION },
    .{ .word = "AUTO", .kw = .AUTO },
    .{ .word = "AUTOINCREMENT", .kw = .AUTOINCREMENT },
    .{ .word = "AUTO_INCREMENT", .kw = .AUTO_INCREMENT },
    .{ .word = "AVG", .kw = .AVG },
    .{ .word = "BACKWARD", .kw = .BACKWARD },
    .{ .word = "BEFORE", .kw = .BEFORE },
    .{ .word = "BEGIN", .kw = .BEGIN },
    .{ .word = "BEGIN_FRAME", .kw = .BEGIN_FRAME },
    .{ .word = "BEGIN_PARTITION", .kw = .BEGIN_PARTITION },
    .{ .word = "BERNOULLI", .kw = .BERNOULLI },
    .{ .word = "BETWEEN", .kw = .BETWEEN },
    .{ .word = "BIGINT", .kw = .BIGINT },
    .{ .word = "BINARY", .kw = .BINARY },
    .{ .word = "BIT", .kw = .BIT },
    .{ .word = "BLOB", .kw = .BLOB },
    .{ .word = "BLOCK", .kw = .BLOCK },
    .{ .word = "BOOL", .kw = .BOOL },
    .{ .word = "BOOLEAN", .kw = .BOOLEAN },
    .{ .word = "BOTH", .kw = .BOTH },
    .{ .word = "BROWSE", .kw = .BROWSE },
    .{ .word = "BTREE", .kw = .BTREE },
    .{ .word = "BUCKET", .kw = .BUCKET },
    .{ .word = "BY", .kw = .BY },
    .{ .word = "BYTES", .kw = .BYTES },
    .{ .word = "CACHE", .kw = .CACHE },
    .{ .word = "CALL", .kw = .CALL },
    .{ .word = "CALLED", .kw = .CALLED },
    .{ .word = "CARDINALITY", .kw = .CARDINALITY },
    .{ .word = "CASCADE", .kw = .CASCADE },
    .{ .word = "CASCADED", .kw = .CASCADED },
    .{ .word = "CASE", .kw = .CASE },
    .{ .word = "CAST", .kw = .CAST },
    .{ .word = "CATALOG", .kw = .CATALOG },
    .{ .word = "CEIL", .kw = .CEIL },
    .{ .word = "CEILING", .kw = .CEILING },
    .{ .word = "CENTURY", .kw = .CENTURY },
    .{ .word = "CHAIN", .kw = .CHAIN },
    .{ .word = "CHANGE", .kw = .CHANGE },
    .{ .word = "CHAR", .kw = .CHAR },
    .{ .word = "CHARACTER", .kw = .CHARACTER },
    .{ .word = "CHARACTERISTICS", .kw = .CHARACTERISTICS },
    .{ .word = "CHARACTERS", .kw = .CHARACTERS },
    .{ .word = "CHARACTER_LENGTH", .kw = .CHARACTER_LENGTH },
    .{ .word = "CHARSET", .kw = .CHARSET },
    .{ .word = "CHAR_LENGTH", .kw = .CHAR_LENGTH },
    .{ .word = "CHECK", .kw = .CHECK },
    .{ .word = "CHECKSUM", .kw = .CHECKSUM },
    .{ .word = "CLOB", .kw = .CLOB },
    .{ .word = "CLONE", .kw = .CLONE },
    .{ .word = "CLOSE", .kw = .CLOSE },
    .{ .word = "CLUSTER", .kw = .CLUSTER },
    .{ .word = "CLUSTERED", .kw = .CLUSTERED },
    .{ .word = "COALESCE", .kw = .COALESCE },
    .{ .word = "COLLATE", .kw = .COLLATE },
    .{ .word = "COLLATION", .kw = .COLLATION },
    .{ .word = "COLLECT", .kw = .COLLECT },
    .{ .word = "COLUMN", .kw = .COLUMN },
    .{ .word = "COLUMNS", .kw = .COLUMNS },
    .{ .word = "COMMENT", .kw = .COMMENT },
    .{ .word = "COMMIT", .kw = .COMMIT },
    .{ .word = "COMMITTED", .kw = .COMMITTED },
    .{ .word = "COMPRESS", .kw = .COMPRESS },
    .{ .word = "COMPRESSION", .kw = .COMPRESSION },
    .{ .word = "COMPUTE", .kw = .COMPUTE },
    .{ .word = "CONDITION", .kw = .CONDITION },
    .{ .word = "CONFLICT", .kw = .CONFLICT },
    .{ .word = "CONNECT", .kw = .CONNECT },
    .{ .word = "CONNECTION", .kw = .CONNECTION },
    .{ .word = "CONSTRAINT", .kw = .CONSTRAINT },
    .{ .word = "CONTAINS", .kw = .CONTAINS },
    .{ .word = "CONTINUE", .kw = .CONTINUE },
    .{ .word = "CONVERT", .kw = .CONVERT },
    .{ .word = "COPY", .kw = .COPY },
    .{ .word = "CORR", .kw = .CORR },
    .{ .word = "CORRESPONDING", .kw = .CORRESPONDING },
    .{ .word = "COUNT", .kw = .COUNT },
    .{ .word = "COVAR_POP", .kw = .COVAR_POP },
    .{ .word = "COVAR_SAMP", .kw = .COVAR_SAMP },
    .{ .word = "CREATE", .kw = .CREATE },
    .{ .word = "CROSS", .kw = .CROSS },
    .{ .word = "CSV", .kw = .CSV },
    .{ .word = "CUBE", .kw = .CUBE },
    .{ .word = "CUME_DIST", .kw = .CUME_DIST },
    .{ .word = "CURRENT", .kw = .CURRENT },
    .{ .word = "CURRENT_CATALOG", .kw = .CURRENT_CATALOG },
    .{ .word = "CURRENT_DATE", .kw = .CURRENT_DATE },
    .{ .word = "CURRENT_DEFAULT_TRANSFORM_GROUP", .kw = .CURRENT_DEFAULT_TRANSFORM_GROUP },
    .{ .word = "CURRENT_PATH", .kw = .CURRENT_PATH },
    .{ .word = "CURRENT_ROLE", .kw = .CURRENT_ROLE },
    .{ .word = "CURRENT_ROW", .kw = .CURRENT_ROW },
    .{ .word = "CURRENT_SCHEMA", .kw = .CURRENT_SCHEMA },
    .{ .word = "CURRENT_TIME", .kw = .CURRENT_TIME },
    .{ .word = "CURRENT_TIMESTAMP", .kw = .CURRENT_TIMESTAMP },
    .{ .word = "CURRENT_TRANSFORM_GROUP_FOR_TYPE", .kw = .CURRENT_TRANSFORM_GROUP_FOR_TYPE },
    .{ .word = "CURRENT_USER", .kw = .CURRENT_USER },
    .{ .word = "CURSOR", .kw = .CURSOR },
    .{ .word = "CYCLE", .kw = .CYCLE },
    .{ .word = "DATA", .kw = .DATA },
    .{ .word = "DATABASE", .kw = .DATABASE },
    .{ .word = "DATABASES", .kw = .DATABASES },
    .{ .word = "DATE", .kw = .DATE },
    .{ .word = "DATETIME", .kw = .DATETIME },
    .{ .word = "DAY", .kw = .DAY },
    .{ .word = "DAYOFWEEK", .kw = .DAYOFWEEK },
    .{ .word = "DAYOFYEAR", .kw = .DAYOFYEAR },
    .{ .word = "DAYS", .kw = .DAYS },
    .{ .word = "DEALLOCATE", .kw = .DEALLOCATE },
    .{ .word = "DEC", .kw = .DEC },
    .{ .word = "DECADE", .kw = .DECADE },
    .{ .word = "DECIMAL", .kw = .DECIMAL },
    .{ .word = "DECLARE", .kw = .DECLARE },
    .{ .word = "DEFAULT", .kw = .DEFAULT },
    .{ .word = "DEFAULTS", .kw = .DEFAULTS },
    .{ .word = "DEFERRABLE", .kw = .DEFERRABLE },
    .{ .word = "DEFERRED", .kw = .DEFERRED },
    .{ .word = "DEFINE", .kw = .DEFINE },
    .{ .word = "DEFINER", .kw = .DEFINER },
    .{ .word = "DELAYED", .kw = .DELAYED },
    .{ .word = "DELETE", .kw = .DELETE },
    .{ .word = "DELIMITER", .kw = .DELIMITER },
    .{ .word = "DENSE_RANK", .kw = .DENSE_RANK },
    .{ .word = "DESC", .kw = .DESC },
    .{ .word = "DESCRIBE", .kw = .DESCRIBE },
    .{ .word = "DETACH", .kw = .DETACH },
    .{ .word = "DETERMINISTIC", .kw = .DETERMINISTIC },
    .{ .word = "DISABLE", .kw = .DISABLE },
    .{ .word = "DISCONNECT", .kw = .DISCONNECT },
    .{ .word = "DISTINCT", .kw = .DISTINCT },
    .{ .word = "DISTINCTROW", .kw = .DISTINCTROW },
    .{ .word = "DISTRIBUTE", .kw = .DISTRIBUTE },
    .{ .word = "DIV", .kw = .DIV },
    .{ .word = "DO", .kw = .DO },
    .{ .word = "DOMAIN", .kw = .DOMAIN },
    .{ .word = "DOUBLE", .kw = .DOUBLE },
    .{ .word = "DROP", .kw = .DROP },
    .{ .word = "DUPLICATE", .kw = .DUPLICATE },
    .{ .word = "DYNAMIC", .kw = .DYNAMIC },
    .{ .word = "EACH", .kw = .EACH },
    .{ .word = "ELEMENT", .kw = .ELEMENT },
    .{ .word = "ELSE", .kw = .ELSE },
    .{ .word = "ELSEIF", .kw = .ELSEIF },
    .{ .word = "EMPTY", .kw = .EMPTY },
    .{ .word = "ENABLE", .kw = .ENABLE },
    .{ .word = "ENCODING", .kw = .ENCODING },
    .{ .word = "ENCRYPTED", .kw = .ENCRYPTED },
    .{ .word = "ENCRYPTION", .kw = .ENCRYPTION },
    .{ .word = "END", .kw = .END },
    .{ .word = "END_FRAME", .kw = .END_FRAME },
    .{ .word = "END_PARTITION", .kw = .END_PARTITION },
    .{ .word = "ENFORCED", .kw = .ENFORCED },
    .{ .word = "ENGINE", .kw = .ENGINE },
    .{ .word = "ENUM", .kw = .ENUM },
    .{ .word = "EPOCH", .kw = .EPOCH },
    .{ .word = "ERROR", .kw = .ERROR },
    .{ .word = "ESCAPE", .kw = .ESCAPE },
    .{ .word = "EXCEPT", .kw = .EXCEPT },
    .{ .word = "EXCEPTION", .kw = .EXCEPTION },
    .{ .word = "EXCLUDE", .kw = .EXCLUDE },
    .{ .word = "EXCLUSIVE", .kw = .EXCLUSIVE },
    .{ .word = "EXEC", .kw = .EXEC },
    .{ .word = "EXECUTE", .kw = .EXECUTE },
    .{ .word = "EXISTS", .kw = .EXISTS },
    .{ .word = "EXP", .kw = .EXP },
    .{ .word = "EXPANSION", .kw = .EXPANSION },
    .{ .word = "EXPLAIN", .kw = .EXPLAIN },
    .{ .word = "EXPLICIT", .kw = .EXPLICIT },
    .{ .word = "EXPORT", .kw = .EXPORT },
    .{ .word = "EXTERNAL", .kw = .EXTERNAL },
    .{ .word = "EXTRACT", .kw = .EXTRACT },
    .{ .word = "FAIL", .kw = .FAIL },
    .{ .word = "FALSE", .kw = .FALSE },
    .{ .word = "FETCH", .kw = .FETCH },
    .{ .word = "FIELDS", .kw = .FIELDS },
    .{ .word = "FILE", .kw = .FILE },
    .{ .word = "FILTER", .kw = .FILTER },
    .{ .word = "FINAL", .kw = .FINAL },
    .{ .word = "FIRST", .kw = .FIRST },
    .{ .word = "FIRST_VALUE", .kw = .FIRST_VALUE },
    .{ .word = "FLOAT", .kw = .FLOAT },
    .{ .word = "FLOAT4", .kw = .FLOAT4 },
    .{ .word = "FLOAT8", .kw = .FLOAT8 },
    .{ .word = "FLOOR", .kw = .FLOOR },
    .{ .word = "FLUSH", .kw = .FLUSH },
    .{ .word = "FOLLOWING", .kw = .FOLLOWING },
    .{ .word = "FOR", .kw = .FOR },
    .{ .word = "FORCE", .kw = .FORCE },
    .{ .word = "FOREIGN", .kw = .FOREIGN },
    .{ .word = "FORMAT", .kw = .FORMAT },
    .{ .word = "FORWARD", .kw = .FORWARD },
    .{ .word = "FRAME_ROW", .kw = .FRAME_ROW },
    .{ .word = "FREE", .kw = .FREE },
    .{ .word = "FROM", .kw = .FROM },
    .{ .word = "FULL", .kw = .FULL },
    .{ .word = "FULLTEXT", .kw = .FULLTEXT },
    .{ .word = "FUNCTION", .kw = .FUNCTION },
    .{ .word = "FUNCTIONS", .kw = .FUNCTIONS },
    .{ .word = "GENERATED", .kw = .GENERATED },
    .{ .word = "GLOBAL", .kw = .GLOBAL },
    .{ .word = "GRANT", .kw = .GRANT },
    .{ .word = "GRANTS", .kw = .GRANTS },
    .{ .word = "GROUP", .kw = .GROUP },
    .{ .word = "GROUPING", .kw = .GROUPING },
    .{ .word = "GROUPS", .kw = .GROUPS },
    .{ .word = "HASH", .kw = .HASH },
    .{ .word = "HAVING", .kw = .HAVING },
    .{ .word = "HEAP", .kw = .HEAP },
    .{ .word = "HIGH_PRIORITY", .kw = .HIGH_PRIORITY },
    .{ .word = "HOLD", .kw = .HOLD },
    .{ .word = "HOUR", .kw = .HOUR },
    .{ .word = "HOURS", .kw = .HOURS },
    .{ .word = "ID", .kw = .ID },
    .{ .word = "IDENTIFIED", .kw = .IDENTIFIED },
    .{ .word = "IDENTITY", .kw = .IDENTITY },
    .{ .word = "IF", .kw = .IF },
    .{ .word = "IGNORE", .kw = .IGNORE },
    .{ .word = "ILIKE", .kw = .ILIKE },
    .{ .word = "IMMEDIATE", .kw = .IMMEDIATE },
    .{ .word = "IMMUTABLE", .kw = .IMMUTABLE },
    .{ .word = "IN", .kw = .IN },
    .{ .word = "INCLUDE", .kw = .INCLUDE },
    .{ .word = "INCREMENT", .kw = .INCREMENT },
    .{ .word = "INDEX", .kw = .INDEX },
    .{ .word = "INDICATOR", .kw = .INDICATOR },
    .{ .word = "INHERIT", .kw = .INHERIT },
    .{ .word = "INHERITS", .kw = .INHERITS },
    .{ .word = "INITIALIZE", .kw = .INITIALIZE },
    .{ .word = "INITIALLY", .kw = .INITIALLY },
    .{ .word = "INNER", .kw = .INNER },
    .{ .word = "INOUT", .kw = .INOUT },
    .{ .word = "INPUT", .kw = .INPUT },
    .{ .word = "INSENSITIVE", .kw = .INSENSITIVE },
    .{ .word = "INSERT", .kw = .INSERT },
    .{ .word = "INSTANT", .kw = .INSTANT },
    .{ .word = "INSTEAD", .kw = .INSTEAD },
    .{ .word = "INT", .kw = .INT },
    .{ .word = "INT2", .kw = .INT2 },
    .{ .word = "INT4", .kw = .INT4 },
    .{ .word = "INT8", .kw = .INT8 },
    .{ .word = "INTEGER", .kw = .INTEGER },
    .{ .word = "INTERSECT", .kw = .INTERSECT },
    .{ .word = "INTERSECTION", .kw = .INTERSECTION },
    .{ .word = "INTERVAL", .kw = .INTERVAL },
    .{ .word = "INTO", .kw = .INTO },
    .{ .word = "INVISIBLE", .kw = .INVISIBLE },
    .{ .word = "INVOKER", .kw = .INVOKER },
    .{ .word = "IS", .kw = .IS },
    .{ .word = "ISOLATION", .kw = .ISOLATION },
    .{ .word = "ITEMS", .kw = .ITEMS },
    .{ .word = "JOIN", .kw = .JOIN },
    .{ .word = "JSON", .kw = .JSON },
    .{ .word = "KEY", .kw = .KEY },
    .{ .word = "KEYS", .kw = .KEYS },
    .{ .word = "KEY_BLOCK_SIZE", .kw = .KEY_BLOCK_SIZE },
    .{ .word = "KILL", .kw = .KILL },
    .{ .word = "LAG", .kw = .LAG },
    .{ .word = "LANGUAGE", .kw = .LANGUAGE },
    .{ .word = "LARGE", .kw = .LARGE },
    .{ .word = "LAST", .kw = .LAST },
    .{ .word = "LAST_VALUE", .kw = .LAST_VALUE },
    .{ .word = "LATERAL", .kw = .LATERAL },
    .{ .word = "LEAD", .kw = .LEAD },
    .{ .word = "LEADING", .kw = .LEADING },
    .{ .word = "LEAKPROOF", .kw = .LEAKPROOF },
    .{ .word = "LEAST", .kw = .LEAST },
    .{ .word = "LEFT", .kw = .LEFT },
    .{ .word = "LEVEL", .kw = .LEVEL },
    .{ .word = "LIKE", .kw = .LIKE },
    .{ .word = "LIKE_REGEX", .kw = .LIKE_REGEX },
    .{ .word = "LIMIT", .kw = .LIMIT },
    .{ .word = "LINES", .kw = .LINES },
    .{ .word = "LIST", .kw = .LIST },
    .{ .word = "LISTEN", .kw = .LISTEN },
    .{ .word = "LN", .kw = .LN },
    .{ .word = "LOAD", .kw = .LOAD },
    .{ .word = "LOCAL", .kw = .LOCAL },
    .{ .word = "LOCALTIME", .kw = .LOCALTIME },
    .{ .word = "LOCALTIMESTAMP", .kw = .LOCALTIMESTAMP },
    .{ .word = "LOCATION", .kw = .LOCATION },
    .{ .word = "LOCK", .kw = .LOCK },
    .{ .word = "LOCKED", .kw = .LOCKED },
    .{ .word = "LOG", .kw = .LOG },
    .{ .word = "LONG", .kw = .LONG },
    .{ .word = "LONGBLOB", .kw = .LONGBLOB },
    .{ .word = "LONGTEXT", .kw = .LONGTEXT },
    .{ .word = "LOWER", .kw = .LOWER },
    .{ .word = "LOW_PRIORITY", .kw = .LOW_PRIORITY },
    .{ .word = "MACRO", .kw = .MACRO },
    .{ .word = "MANAGE", .kw = .MANAGE },
    .{ .word = "MANAGED", .kw = .MANAGED },
    .{ .word = "MAP", .kw = .MAP },
    .{ .word = "MATCH", .kw = .MATCH },
    .{ .word = "MATCHED", .kw = .MATCHED },
    .{ .word = "MATCH_RECOGNIZE", .kw = .MATCH_RECOGNIZE },
    .{ .word = "MATERIALIZED", .kw = .MATERIALIZED },
    .{ .word = "MAX", .kw = .MAX },
    .{ .word = "MAXVALUE", .kw = .MAXVALUE },
    .{ .word = "MAX_ROWS", .kw = .MAX_ROWS },
    .{ .word = "MEDIUMBLOB", .kw = .MEDIUMBLOB },
    .{ .word = "MEDIUMINT", .kw = .MEDIUMINT },
    .{ .word = "MEDIUMTEXT", .kw = .MEDIUMTEXT },
    .{ .word = "MEMBER", .kw = .MEMBER },
    .{ .word = "MERGE", .kw = .MERGE },
    .{ .word = "METHOD", .kw = .METHOD },
    .{ .word = "MICROSECOND", .kw = .MICROSECOND },
    .{ .word = "MICROSECONDS", .kw = .MICROSECONDS },
    .{ .word = "MILLENNIUM", .kw = .MILLENNIUM },
    .{ .word = "MILLISECOND", .kw = .MILLISECOND },
    .{ .word = "MILLISECONDS", .kw = .MILLISECONDS },
    .{ .word = "MIN", .kw = .MIN },
    .{ .word = "MINUS", .kw = .MINUS },
    .{ .word = "MINUTE", .kw = .MINUTE },
    .{ .word = "MINUTES", .kw = .MINUTES },
    .{ .word = "MINVALUE", .kw = .MINVALUE },
    .{ .word = "MIN_ROWS", .kw = .MIN_ROWS },
    .{ .word = "MOD", .kw = .MOD },
    .{ .word = "MODE", .kw = .MODE },
    .{ .word = "MODIFIES", .kw = .MODIFIES },
    .{ .word = "MODIFY", .kw = .MODIFY },
    .{ .word = "MODULE", .kw = .MODULE },
    .{ .word = "MONITOR", .kw = .MONITOR },
    .{ .word = "MONTH", .kw = .MONTH },
    .{ .word = "MONTHS", .kw = .MONTHS },
    .{ .word = "MULTISET", .kw = .MULTISET },
    .{ .word = "NAME", .kw = .NAME },
    .{ .word = "NAMES", .kw = .NAMES },
    .{ .word = "NANOSECOND", .kw = .NANOSECOND },
    .{ .word = "NANOSECONDS", .kw = .NANOSECONDS },
    .{ .word = "NATIONAL", .kw = .NATIONAL },
    .{ .word = "NATURAL", .kw = .NATURAL },
    .{ .word = "NCHAR", .kw = .NCHAR },
    .{ .word = "NCLOB", .kw = .NCLOB },
    .{ .word = "NEXT", .kw = .NEXT },
    .{ .word = "NO", .kw = .NO },
    .{ .word = "NOCYCLE", .kw = .NOCYCLE },
    .{ .word = "NONE", .kw = .NONE },
    .{ .word = "NORMALIZE", .kw = .NORMALIZE },
    .{ .word = "NORMALIZED", .kw = .NORMALIZED },
    .{ .word = "NOT", .kw = .NOT },
    .{ .word = "NOTHING", .kw = .NOTHING },
    .{ .word = "NOTIFY", .kw = .NOTIFY },
    .{ .word = "NOWAIT", .kw = .NOWAIT },
    .{ .word = "NO_WRITE_TO_BINLOG", .kw = .NO_WRITE_TO_BINLOG },
    .{ .word = "NTH_VALUE", .kw = .NTH_VALUE },
    .{ .word = "NTILE", .kw = .NTILE },
    .{ .word = "NULL", .kw = .NULL },
    .{ .word = "NULLABLE", .kw = .NULLABLE },
    .{ .word = "NULLIF", .kw = .NULLIF },
    .{ .word = "NULLS", .kw = .NULLS },
    .{ .word = "NUMBER", .kw = .NUMBER },
    .{ .word = "NUMERIC", .kw = .NUMERIC },
    .{ .word = "NVARCHAR", .kw = .NVARCHAR },
    .{ .word = "OBJECT", .kw = .OBJECT },
    .{ .word = "OCCURRENCES_REGEX", .kw = .OCCURRENCES_REGEX },
    .{ .word = "OCTETS", .kw = .OCTETS },
    .{ .word = "OCTET_LENGTH", .kw = .OCTET_LENGTH },
    .{ .word = "OF", .kw = .OF },
    .{ .word = "OFF", .kw = .OFF },
    .{ .word = "OFFSET", .kw = .OFFSET },
    .{ .word = "OLD", .kw = .OLD },
    .{ .word = "OMIT", .kw = .OMIT },
    .{ .word = "ON", .kw = .ON },
    .{ .word = "ONE", .kw = .ONE },
    .{ .word = "ONLY", .kw = .ONLY },
    .{ .word = "OPEN", .kw = .OPEN },
    .{ .word = "OPERATE", .kw = .OPERATE },
    .{ .word = "OPERATOR", .kw = .OPERATOR },
    .{ .word = "OPTIMIZE", .kw = .OPTIMIZE },
    .{ .word = "OPTION", .kw = .OPTION },
    .{ .word = "OPTIONS", .kw = .OPTIONS },
    .{ .word = "OR", .kw = .OR },
    .{ .word = "ORDER", .kw = .ORDER },
    .{ .word = "ORDINALITY", .kw = .ORDINALITY },
    .{ .word = "OTHER", .kw = .OTHER },
    .{ .word = "OUT", .kw = .OUT },
    .{ .word = "OUTER", .kw = .OUTER },
    .{ .word = "OUTPUT", .kw = .OUTPUT },
    .{ .word = "OVER", .kw = .OVER },
    .{ .word = "OVERFLOW", .kw = .OVERFLOW },
    .{ .word = "OVERLAPS", .kw = .OVERLAPS },
    .{ .word = "OVERLAY", .kw = .OVERLAY },
    .{ .word = "OVERRIDE", .kw = .OVERRIDE },
    .{ .word = "OVERWRITE", .kw = .OVERWRITE },
    .{ .word = "OWNED", .kw = .OWNED },
    .{ .word = "OWNER", .kw = .OWNER },
    .{ .word = "PARALLEL", .kw = .PARALLEL },
    .{ .word = "PARAMETER", .kw = .PARAMETER },
    .{ .word = "PARTIAL", .kw = .PARTIAL },
    .{ .word = "PARTITION", .kw = .PARTITION },
    .{ .word = "PARTITIONED", .kw = .PARTITIONED },
    .{ .word = "PARTITIONS", .kw = .PARTITIONS },
    .{ .word = "PASSING", .kw = .PASSING },
    .{ .word = "PASSWORD", .kw = .PASSWORD },
    .{ .word = "PATH", .kw = .PATH },
    .{ .word = "PATTERN", .kw = .PATTERN },
    .{ .word = "PER", .kw = .PER },
    .{ .word = "PERCENT", .kw = .PERCENT },
    .{ .word = "PERCENTILE_CONT", .kw = .PERCENTILE_CONT },
    .{ .word = "PERCENTILE_DISC", .kw = .PERCENTILE_DISC },
    .{ .word = "PERCENT_RANK", .kw = .PERCENT_RANK },
    .{ .word = "PERIOD", .kw = .PERIOD },
    .{ .word = "PIVOT", .kw = .PIVOT },
    .{ .word = "PLACING", .kw = .PLACING },
    .{ .word = "POLICY", .kw = .POLICY },
    .{ .word = "POOL", .kw = .POOL },
    .{ .word = "POSITION", .kw = .POSITION },
    .{ .word = "POSITION_REGEX", .kw = .POSITION_REGEX },
    .{ .word = "POWER", .kw = .POWER },
    .{ .word = "PRECEDING", .kw = .PRECEDING },
    .{ .word = "PRECISION", .kw = .PRECISION },
    .{ .word = "PREPARE", .kw = .PREPARE },
    .{ .word = "PRESERVE", .kw = .PRESERVE },
    .{ .word = "PRIMARY", .kw = .PRIMARY },
    .{ .word = "PRIOR", .kw = .PRIOR },
    .{ .word = "PRIVILEGES", .kw = .PRIVILEGES },
    .{ .word = "PROCEDURE", .kw = .PROCEDURE },
    .{ .word = "PUBLIC", .kw = .PUBLIC },
    .{ .word = "PURGE", .kw = .PURGE },
    .{ .word = "QUALIFY", .kw = .QUALIFY },
    .{ .word = "QUARTER", .kw = .QUARTER },
    .{ .word = "QUERIES", .kw = .QUERIES },
    .{ .word = "QUERY", .kw = .QUERY },
    .{ .word = "QUOTE", .kw = .QUOTE },
    .{ .word = "RAISE", .kw = .RAISE },
    .{ .word = "RANGE", .kw = .RANGE },
    .{ .word = "RANK", .kw = .RANK },
    .{ .word = "READ", .kw = .READ },
    .{ .word = "READS", .kw = .READS },
    .{ .word = "READ_ONLY", .kw = .READ_ONLY },
    .{ .word = "REAL", .kw = .REAL },
    .{ .word = "RECURSIVE", .kw = .RECURSIVE },
    .{ .word = "REF", .kw = .REF },
    .{ .word = "REFERENCES", .kw = .REFERENCES },
    .{ .word = "REFERENCING", .kw = .REFERENCING },
    .{ .word = "REFRESH", .kw = .REFRESH },
    .{ .word = "REGEXP", .kw = .REGEXP },
    .{ .word = "REGR_AVGX", .kw = .REGR_AVGX },
    .{ .word = "REGR_AVGY", .kw = .REGR_AVGY },
    .{ .word = "REGR_COUNT", .kw = .REGR_COUNT },
    .{ .word = "REGR_INTERCEPT", .kw = .REGR_INTERCEPT },
    .{ .word = "REGR_R2", .kw = .REGR_R2 },
    .{ .word = "REGR_SLOPE", .kw = .REGR_SLOPE },
    .{ .word = "REGR_SXX", .kw = .REGR_SXX },
    .{ .word = "REGR_SXY", .kw = .REGR_SXY },
    .{ .word = "REGR_SYY", .kw = .REGR_SYY },
    .{ .word = "RELATIVE", .kw = .RELATIVE },
    .{ .word = "RELEASE", .kw = .RELEASE },
    .{ .word = "REMAINDER", .kw = .REMAINDER },
    .{ .word = "REMOTE", .kw = .REMOTE },
    .{ .word = "RENAME", .kw = .RENAME },
    .{ .word = "REPEATABLE", .kw = .REPEATABLE },
    .{ .word = "REPLACE", .kw = .REPLACE },
    .{ .word = "REPLICA", .kw = .REPLICA },
    .{ .word = "REPLICATE", .kw = .REPLICATE },
    .{ .word = "REPLICATION", .kw = .REPLICATION },
    .{ .word = "REQUIRE", .kw = .REQUIRE },
    .{ .word = "RESET", .kw = .RESET },
    .{ .word = "RESTRICT", .kw = .RESTRICT },
    .{ .word = "RESULT", .kw = .RESULT },
    .{ .word = "RETURN", .kw = .RETURN },
    .{ .word = "RETURNING", .kw = .RETURNING },
    .{ .word = "RETURNS", .kw = .RETURNS },
    .{ .word = "REVOKE", .kw = .REVOKE },
    .{ .word = "RIGHT", .kw = .RIGHT },
    .{ .word = "RLIKE", .kw = .RLIKE },
    .{ .word = "ROLE", .kw = .ROLE },
    .{ .word = "ROLES", .kw = .ROLES },
    .{ .word = "ROLLBACK", .kw = .ROLLBACK },
    .{ .word = "ROLLUP", .kw = .ROLLUP },
    .{ .word = "ROW", .kw = .ROW },
    .{ .word = "ROWID", .kw = .ROWID },
    .{ .word = "ROWS", .kw = .ROWS },
    .{ .word = "ROW_FORMAT", .kw = .ROW_FORMAT },
    .{ .word = "ROW_NUMBER", .kw = .ROW_NUMBER },
    .{ .word = "SAFE", .kw = .SAFE },
    .{ .word = "SAMPLE", .kw = .SAMPLE },
    .{ .word = "SAVEPOINT", .kw = .SAVEPOINT },
    .{ .word = "SCHEMA", .kw = .SCHEMA },
    .{ .word = "SCHEMAS", .kw = .SCHEMAS },
    .{ .word = "SCOPE", .kw = .SCOPE },
    .{ .word = "SCROLL", .kw = .SCROLL },
    .{ .word = "SEARCH", .kw = .SEARCH },
    .{ .word = "SECOND", .kw = .SECOND },
    .{ .word = "SECONDS", .kw = .SECONDS },
    .{ .word = "SECURITY", .kw = .SECURITY },
    .{ .word = "SELECT", .kw = .SELECT },
    .{ .word = "SEMI", .kw = .SEMI },
    .{ .word = "SENSITIVE", .kw = .SENSITIVE },
    .{ .word = "SEPARATOR", .kw = .SEPARATOR },
    .{ .word = "SEQUENCE", .kw = .SEQUENCE },
    .{ .word = "SEQUENCES", .kw = .SEQUENCES },
    .{ .word = "SERIALIZABLE", .kw = .SERIALIZABLE },
    .{ .word = "SERVER", .kw = .SERVER },
    .{ .word = "SERVICE", .kw = .SERVICE },
    .{ .word = "SESSION", .kw = .SESSION },
    .{ .word = "SESSION_USER", .kw = .SESSION_USER },
    .{ .word = "SET", .kw = .SET },
    .{ .word = "SETS", .kw = .SETS },
    .{ .word = "SHARE", .kw = .SHARE },
    .{ .word = "SHOW", .kw = .SHOW },
    .{ .word = "SIGNED", .kw = .SIGNED },
    .{ .word = "SIMILAR", .kw = .SIMILAR },
    .{ .word = "SMALLINT", .kw = .SMALLINT },
    .{ .word = "SNAPSHOT", .kw = .SNAPSHOT },
    .{ .word = "SOME", .kw = .SOME },
    .{ .word = "SORT", .kw = .SORT },
    .{ .word = "SPATIAL", .kw = .SPATIAL },
    .{ .word = "SQL", .kw = .SQL },
    .{ .word = "SQLEXCEPTION", .kw = .SQLEXCEPTION },
    .{ .word = "SQLSTATE", .kw = .SQLSTATE },
    .{ .word = "SQLWARNING", .kw = .SQLWARNING },
    .{ .word = "SQL_BIG_RESULT", .kw = .SQL_BIG_RESULT },
    .{ .word = "SQL_CALC_FOUND_ROWS", .kw = .SQL_CALC_FOUND_ROWS },
    .{ .word = "SQL_NO_CACHE", .kw = .SQL_NO_CACHE },
    .{ .word = "SQL_SMALL_RESULT", .kw = .SQL_SMALL_RESULT },
    .{ .word = "SQRT", .kw = .SQRT },
    .{ .word = "STABLE", .kw = .STABLE },
    .{ .word = "START", .kw = .START },
    .{ .word = "STARTS", .kw = .STARTS },
    .{ .word = "STATEMENT", .kw = .STATEMENT },
    .{ .word = "STATIC", .kw = .STATIC },
    .{ .word = "STATISTICS", .kw = .STATISTICS },
    .{ .word = "STATUS", .kw = .STATUS },
    .{ .word = "STDDEV_POP", .kw = .STDDEV_POP },
    .{ .word = "STDDEV_SAMP", .kw = .STDDEV_SAMP },
    .{ .word = "STDIN", .kw = .STDIN },
    .{ .word = "STDOUT", .kw = .STDOUT },
    .{ .word = "STORAGE", .kw = .STORAGE },
    .{ .word = "STORED", .kw = .STORED },
    .{ .word = "STRAIGHT_JOIN", .kw = .STRAIGHT_JOIN },
    .{ .word = "STREAM", .kw = .STREAM },
    .{ .word = "STRICT", .kw = .STRICT },
    .{ .word = "STRING", .kw = .STRING },
    .{ .word = "STRUCT", .kw = .STRUCT },
    .{ .word = "SUBMULTISET", .kw = .SUBMULTISET },
    .{ .word = "SUBSTR", .kw = .SUBSTR },
    .{ .word = "SUBSTRING", .kw = .SUBSTRING },
    .{ .word = "SUBSTRING_REGEX", .kw = .SUBSTRING_REGEX },
    .{ .word = "SUCCEEDS", .kw = .SUCCEEDS },
    .{ .word = "SUM", .kw = .SUM },
    .{ .word = "SUPER", .kw = .SUPER },
    .{ .word = "SUPERUSER", .kw = .SUPERUSER },
    .{ .word = "SUSPEND", .kw = .SUSPEND },
    .{ .word = "SYMMETRIC", .kw = .SYMMETRIC },
    .{ .word = "SYNONYM", .kw = .SYNONYM },
    .{ .word = "SYSTEM", .kw = .SYSTEM },
    .{ .word = "SYSTEM_TIME", .kw = .SYSTEM_TIME },
    .{ .word = "SYSTEM_USER", .kw = .SYSTEM_USER },
    .{ .word = "TABLE", .kw = .TABLE },
    .{ .word = "TABLES", .kw = .TABLES },
    .{ .word = "TABLESAMPLE", .kw = .TABLESAMPLE },
    .{ .word = "TABLESPACE", .kw = .TABLESPACE },
    .{ .word = "TEMP", .kw = .TEMP },
    .{ .word = "TEMPORARY", .kw = .TEMPORARY },
    .{ .word = "TEMPTABLE", .kw = .TEMPTABLE },
    .{ .word = "TERMINATED", .kw = .TERMINATED },
    .{ .word = "TEXT", .kw = .TEXT },
    .{ .word = "THEN", .kw = .THEN },
    .{ .word = "TIES", .kw = .TIES },
    .{ .word = "TIME", .kw = .TIME },
    .{ .word = "TIMESTAMP", .kw = .TIMESTAMP },
    .{ .word = "TIMESTAMPTZ", .kw = .TIMESTAMPTZ },
    .{ .word = "TIMETZ", .kw = .TIMETZ },
    .{ .word = "TIMEZONE", .kw = .TIMEZONE },
    .{ .word = "TIMEZONE_HOUR", .kw = .TIMEZONE_HOUR },
    .{ .word = "TIMEZONE_MINUTE", .kw = .TIMEZONE_MINUTE },
    .{ .word = "TINYBLOB", .kw = .TINYBLOB },
    .{ .word = "TINYINT", .kw = .TINYINT },
    .{ .word = "TINYTEXT", .kw = .TINYTEXT },
    .{ .word = "TO", .kw = .TO },
    .{ .word = "TOP", .kw = .TOP },
    .{ .word = "TRAILING", .kw = .TRAILING },
    .{ .word = "TRANSACTION", .kw = .TRANSACTION },
    .{ .word = "TRANSLATE", .kw = .TRANSLATE },
    .{ .word = "TRANSLATE_REGEX", .kw = .TRANSLATE_REGEX },
    .{ .word = "TRANSLATION", .kw = .TRANSLATION },
    .{ .word = "TREAT", .kw = .TREAT },
    .{ .word = "TRIGGER", .kw = .TRIGGER },
    .{ .word = "TRIM", .kw = .TRIM },
    .{ .word = "TRIM_ARRAY", .kw = .TRIM_ARRAY },
    .{ .word = "TRUE", .kw = .TRUE },
    .{ .word = "TRUNCATE", .kw = .TRUNCATE },
    .{ .word = "TRY", .kw = .TRY },
    .{ .word = "TRY_CAST", .kw = .TRY_CAST },
    .{ .word = "TYPE", .kw = .TYPE },
    .{ .word = "UBIGINT", .kw = .UBIGINT },
    .{ .word = "UNBOUNDED", .kw = .UNBOUNDED },
    .{ .word = "UNCOMMITTED", .kw = .UNCOMMITTED },
    .{ .word = "UNION", .kw = .UNION },
    .{ .word = "UNIQUE", .kw = .UNIQUE },
    .{ .word = "UNKNOWN", .kw = .UNKNOWN },
    .{ .word = "UNLOCK", .kw = .UNLOCK },
    .{ .word = "UNMATCHED", .kw = .UNMATCHED },
    .{ .word = "UNNEST", .kw = .UNNEST },
    .{ .word = "UNPIVOT", .kw = .UNPIVOT },
    .{ .word = "UNSIGNED", .kw = .UNSIGNED },
    .{ .word = "UNTIL", .kw = .UNTIL },
    .{ .word = "UPDATE", .kw = .UPDATE },
    .{ .word = "UPPER", .kw = .UPPER },
    .{ .word = "USE", .kw = .USE },
    .{ .word = "USER", .kw = .USER },
    .{ .word = "USING", .kw = .USING },
    .{ .word = "UUID", .kw = .UUID },
    .{ .word = "VACUUM", .kw = .VACUUM },
    .{ .word = "VALID", .kw = .VALID },
    .{ .word = "VALIDATE", .kw = .VALIDATE },
    .{ .word = "VALUE", .kw = .VALUE },
    .{ .word = "VALUES", .kw = .VALUES },
    .{ .word = "VARBINARY", .kw = .VARBINARY },
    .{ .word = "VARCHAR", .kw = .VARCHAR },
    .{ .word = "VARCHAR2", .kw = .VARCHAR2 },
    .{ .word = "VARIABLE", .kw = .VARIABLE },
    .{ .word = "VARIABLES", .kw = .VARIABLES },
    .{ .word = "VARYING", .kw = .VARYING },
    .{ .word = "VAR_POP", .kw = .VAR_POP },
    .{ .word = "VAR_SAMP", .kw = .VAR_SAMP },
    .{ .word = "VERSION", .kw = .VERSION },
    .{ .word = "VERSIONING", .kw = .VERSIONING },
    .{ .word = "VIEW", .kw = .VIEW },
    .{ .word = "VIEWS", .kw = .VIEWS },
    .{ .word = "VOLATILE", .kw = .VOLATILE },
    .{ .word = "WEEK", .kw = .WEEK },
    .{ .word = "WEEKS", .kw = .WEEKS },
    .{ .word = "WHEN", .kw = .WHEN },
    .{ .word = "WHERE", .kw = .WHERE },
    .{ .word = "WHILE", .kw = .WHILE },
    .{ .word = "WIDTH_BUCKET", .kw = .WIDTH_BUCKET },
    .{ .word = "WINDOW", .kw = .WINDOW },
    .{ .word = "WITH", .kw = .WITH },
    .{ .word = "WITHIN", .kw = .WITHIN },
    .{ .word = "WITHOUT", .kw = .WITHOUT },
    .{ .word = "WORK", .kw = .WORK },
    .{ .word = "WRITE", .kw = .WRITE },
    .{ .word = "XOR", .kw = .XOR },
    .{ .word = "YEAR", .kw = .YEAR },
    .{ .word = "YEARS", .kw = .YEARS },
    .{ .word = "ZONE", .kw = .ZONE },
};

/// Look up a keyword by its uppercase string. Returns NoKeyword if not found.
/// The input must already be uppercase ASCII.
pub fn lookupKeyword(word: []const u8) Keyword {
    var lo: usize = 0;
    var hi: usize = ALL_KEYWORDS.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const cmp = std.mem.order(u8, ALL_KEYWORDS[mid].word, word);
        switch (cmp) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return ALL_KEYWORDS[mid].kw,
        }
    }
    return .NoKeyword;
}

/// Look up a keyword from any-case input. Performs an uppercase comparison.
pub fn lookupKeywordCaseInsensitive(word: []const u8) Keyword {
    // Stack buffer for small words; heap-less for up to 64 chars
    var buf: [128]u8 = undefined;
    if (word.len > buf.len) return .NoKeyword;
    const upper = std.ascii.upperString(buf[0..word.len], word);
    return lookupKeyword(upper);
}

/// Keywords that cannot be used as a table alias in FROM/JOIN position.
/// Ported from Rust's RESERVED_FOR_TABLE_ALIAS.
pub const RESERVED_FOR_TABLE_ALIAS: []const Keyword = &.{
    .WITH,
    .EXPLAIN,
    .ANALYZE,
    .SELECT,
    .WHERE,
    .GROUP,
    .SORT,
    .HAVING,
    .ORDER,
    .PIVOT,
    .UNPIVOT,
    .TOP,
    .LATERAL,
    .VIEW,
    .LIMIT,
    .OFFSET,
    .FETCH,
    .UNION,
    .EXCEPT,
    .INTERSECT,
    .MINUS,
    .ON,
    .JOIN,
    .INNER,
    .CROSS,
    .FULL,
    .LEFT,
    .RIGHT,
    .NATURAL,
    .USING,
    .CLUSTER,
    .DISTRIBUTE,
    .GLOBAL,
    .ANTI,
    .SEMI,
    .RETURNING,
    .ASOF,
    .MATCH_RECOGNIZE,
    .OUTER,
    .SET,
    .QUALIFY,
    .WINDOW,
    .END,
    .FOR,
    .PARTITION,
    .START,
    .CONNECT,
    .SAMPLE,
    .TABLESAMPLE,
    .FROM,
    .OPEN,
};

/// Keywords that cannot be used as a column alias.
pub const RESERVED_FOR_COLUMN_ALIAS: []const Keyword = &.{
    .WITH,
    .EXPLAIN,
    .ANALYZE,
    .SELECT,
    .WHERE,
    .GROUP,
    .SORT,
    .HAVING,
    .ORDER,
    .LIMIT,
    .OFFSET,
    .FETCH,
    .UNION,
    .EXCEPT,
    .INTERSECT,
    .MINUS,
    .FROM,
};

test "keyword lookup - basic" {
    try std.testing.expectEqual(Keyword.SELECT, lookupKeyword("SELECT"));
    try std.testing.expectEqual(Keyword.WHERE, lookupKeyword("WHERE"));
    try std.testing.expectEqual(Keyword.FROM, lookupKeyword("FROM"));
    try std.testing.expectEqual(Keyword.INSERT, lookupKeyword("INSERT"));
    try std.testing.expectEqual(Keyword.UPDATE, lookupKeyword("UPDATE"));
    try std.testing.expectEqual(Keyword.DELETE, lookupKeyword("DELETE"));
    try std.testing.expectEqual(Keyword.CREATE, lookupKeyword("CREATE"));
    try std.testing.expectEqual(Keyword.DROP, lookupKeyword("DROP"));
    try std.testing.expectEqual(Keyword.ALTER, lookupKeyword("ALTER"));
    try std.testing.expectEqual(Keyword.AUTO_INCREMENT, lookupKeyword("AUTO_INCREMENT"));
}

test "keyword lookup - not found" {
    try std.testing.expectEqual(Keyword.NoKeyword, lookupKeyword("FOOBAR"));
    try std.testing.expectEqual(Keyword.NoKeyword, lookupKeyword(""));
    try std.testing.expectEqual(Keyword.NoKeyword, lookupKeyword("SELECTX"));
}

test "keyword lookup - case insensitive" {
    try std.testing.expectEqual(Keyword.SELECT, lookupKeywordCaseInsensitive("select"));
    try std.testing.expectEqual(Keyword.SELECT, lookupKeywordCaseInsensitive("Select"));
    try std.testing.expectEqual(Keyword.WHERE, lookupKeywordCaseInsensitive("where"));
    try std.testing.expectEqual(Keyword.AUTO_INCREMENT, lookupKeywordCaseInsensitive("auto_increment"));
}

test "ALL_KEYWORDS is sorted" {
    var i: usize = 1;
    while (i < ALL_KEYWORDS.len) : (i += 1) {
        const prev = ALL_KEYWORDS[i - 1].word;
        const curr = ALL_KEYWORDS[i].word;
        try std.testing.expect(std.mem.lessThan(u8, prev, curr));
    }
}
